language: ruby
rvm:
- 2.6.3
addons:
  firefox: "62.0.2"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
